### ISSUE TITLE
Замечания по коду

### ISSUE THREAD

**Issue by sergey-shambir** [AnatolyKorablyov/TP_lab7#1]
- константу PI не надо объявлять, надо использовать M_PI из заголовка <cmath>. Чтобы избавиться от особенностей <cmath> в Visual C++, надо использовать: http://stackoverflow.com/questions/6563810/m-pi-works-with-math-h-but-not-with-cmath-in-visual-studio
- вместо объявления ```float coordX = -10, coordY = 10;``` в одной строке лучше использовать тип данных sf::Vector2f
- то же самое касается ```float arrayX[60], arrayY[60];```
- число 60 фигурирует в коде слишком часто, надо переместить в именованную константу

**Comment by AnatolyKorablyov** [comment]
Исправил

**Comment by sergey-shambir** [comment]
Принято
